### PR TITLE
Feature Request

### PR DESCRIPTION
**Pull request by brasilikum**
Hey, as Issues are not allowed (is that on purpose?), I wanted to propose the following feature, but maybe it is out of scope:

# Problem
I have two headphones:
One of them can only connect to one device at a time. That one I would like to disconnect on snooze.
The other one can connect to two devices at a time. That one I would like not to disconnect on snooze.

# Possible Solution
I am aware that blueznooze currently totally disables bluetooth. This feature would require to selectively disconnect devices

# Alternatives
It might be possible to achieve this with another tool, for example http://www.hammerspoon.org/

### CODE REVIEW

**Comment by henhal** [comment]
This would be awesome as well because I suspect Bluesnooze is the reason I can't wake up my Mac M1 using my BT mouse/kbd (which makes sense), but I love how it disconnects my headphones which would otherwise be drained of battery every day. 

I guess this is very different from disabling the entire BT adapter, but an option to force disconnect of _selected devices only_ where I could choose to only disconnect my headphones would be AWESOME.

**Comment by fmckeogh** [comment]
@henhal Yeah that's my exact need too, it's just my headphones that I accidentally leave on all day because I forget to turn them off. But they turn off automatically if my Mac were to disconnect before sleeping.

**Comment by hzmsrv** [comment]
even if this is for Bluetooth! but if it could add some function to make sure the OS sleep will perfect!  my MBP always no sleep when my lid is closed

**Comment by fmckeogh** [comment]
@henhal I wrote this really simple app to do what I wanted, might be of use to you too:) https://github.com/fmckeogh/hedy

**Comment by henhal** [comment]
@fmckeogh Cool, will check it out. Do you have a description, as there's no README etc?

**Comment by fmckeogh** [comment]
@henhal oh sorry yeah pushing a tidy-up commit in a sec. Usually you'd add the program to your login items, it runs in the background with two observers for screen unlocking and locking, connecting and disconnecting respectively.

**Comment by singalen** [comment]
Sorry, issues are not open, so leaving a comment here.
Can you please put a license on this product? It should help use it in a corporate environment. Like, switch my favorite headphones between work and personal laptops.

**Comment by odlp** [comment]
Heya going to close this since I don't want to keep adding features to this simple tool which meets my needs. Selectively disconnecting specific Bluetooth devices would by neat but at the same time it'd need a complete rewrite (this app simply toggles the power state of Bluetooth on / off).

**Comment by odlp** [comment]
@singalen sorry for the delay - added an MIT license in 513c87a7675d32aa07ddb9e72ca69a55534bd750

**Pull request closed without merging**
